services:
  dev-db:
    container_name: database_container
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  server:
    container_name: server_container
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - dev-db
    environment:
      DATABASE_URL: ${DATABASE_URL}

  migration:
    container_name: migrator
    build: .
    depends_on: 
      - dev-db
    command: sh -c '/usr/local/bin/wait-for-it.sh dev-db:5432 -- npx prisma migrate dev'
