services:
  dev-db:
    container_name: database_container
    image: postgres:latest
    restart: always
    ports:
      - 2345:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  server:
    container_name: server_container
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - dev-db
    environment:
      DATABASE_URL: ${DATABASE_URL}
